### ISSUE TITLE
Wrong column names in "getphasey_dpp_'+str(k+1)+'.out"

### ISSUE THREAD

**Issue by vimaier** [pylhc/Beta-Beat.src#17]
@rogeliotomas @Eothred @alangner 
Can you check the following?
In GetLLM in the section "Phase, Beta and coupling for non-zero DPP"(around 4930) the files <b>getbetax_dpp_'+str(k+1)+'.out</b> and <b>getbetay_dpp_'+str(k+1)+'.out</b> will be created. 
I think the column names in the y file are wrong. Instead of BET>Y< and so on, there is BET>X<.

See the x-file:

``` python
filename = 'getbetax_dpp_'+str(k+1)+'.out'
...
tfs_file.add_column_names(["NAME","S","COUNT","BETX","ERRBETX","STDBETX","ALFX","ERRALFX","STDALFX","BETXMDL","ALFXMDL","
```

See the y-file(also BET>X<...):

``` python
filename = 'getbetay_dpp_'+str(k+1)+'.out'
...
tfs_file.add_column_names(["NAME","S","COUNT","BETX","ERRBETX","STDBETX","ALFX","ERRALFX","STDALFX","BETXMDL","ALFXMDL","
```

I assume all characters 'X' have to be replaced by 'Y'.  Can you validate it?

**Comment by JoschD** [comment]
Closed as all column names are correct in GetLLM.py now.
