### ISSUE TITLE
Wrong source file names in "getCOy_dpp_'+str(k+1)+'.out"?

### ISSUE THREAD

**Issue by vimaier** [pylhc/Beta-Beat.src#18]
@rogeliotomas @Eothred @alangner 
I found a small(?) discrepancy in GetLLM(around 4739-4760)
The for-loop iterates over "ListOf>Non<ZeroDPPY" but len(ListOfZeroDPPY) will be written into the third column:

``` python
for j in ListOfNonZeroDPPY:    
...        
            for i in range(0,len(bpms)):
...         
                list_row_entries = ['"'+bn1+'"',bns1, len(ListOfZeroDPPY), codpp[bn1][0], codpp[bn1][1], MADTwiss.Y[MADTwiss.indx[bn1]], MADTwiss.MUY[MADTwiss.indx[bn1]] ]

```

It looks like it should be len(ListOfNonZeroDPPY).

Can you checkt it?

**Comment by JoschD** [comment]
This loop is not used in GetLLM anymore.
