### ISSUE TITLE
Clearly erroneous statement in GetLLM.py

### ISSUE THREAD

**Issue by piotrskowronski** [pylhc/Beta-Beat.src#187]
Eclipse claims that this line is simply wrong, and Jaime confirms that,
https://github.com/pylhc/Beta-Beat.src/blob/40162ff6bd60a140f2b00ee72b1a19cf1ace3c70/GetLLM/GetLLM.py#L578

![image](https://user-images.githubusercontent.com/16878140/52268793-abe1f680-293c-11e9-84e0-c4947bda5dd8.png)

**Comment by JoschD** [comment]
This is actually just shitty code, not wrong code. The dictionary is defined in a file, that is called via execfile. 
I think we haven't been using this for a while ... will be removed in the new optics analysis.
