### ISSUE TITLE
[Bug]: LHC Error definition files are taken incorrectly

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/Beta-Beat.src#229]
### Bug Description

The hard-coded location of the error definition files for the LHC, used in model creation, points to the wrong location (an old `omc3` repo that is not updated as we don't have write rights to it).

As a consequence, when trying to create a model for 2022 6.8TeV, the symlink `error_deff.txt` points to a non-existant file.
See the attached screenshot.

<img width="1077" alt="Screenshot 2022-04-25 at 22 24 04" src="https://user-images.githubusercontent.com/19598248/165168946-5ac64081-fd93-44da-880f-0be436b2d76b.png">

### Steps to Reproduce

Do model creation for LHCB[12], 2022 at 6.8TeV and require b2 errors.

### Possible Fix Implementation

Point to the right `omc3`, which is in `/afs/cern.ch/eng/sl/lintrack/omc_repositories/omc3`.
I will make a PR to fix this shortly.

**Comment by tpersson** [comment]
All good to update the error_defs for 6.8TeV

**Comment by fsoubelet** [comment]
Closed by #230
