### ISSUE TITLE
Merge of lhc.py failed

### ISSUE THREAD

**Issue by awegsche** [pylhc/Beta-Beat.src#67]
Because of a significant amount of code moved from get_class to __init__, the merging scrambled up the code.

It should be fixed. But please check. 
And what is EntryPoint ?

**Comment by jaimecp89** [comment]
This has been fixed in c57db1dbb7858088aa73d9c811b44760d25dd533 right? @awegsche @JoschD

**Comment by JoschD** [comment]
Fixed with #70 and some handiwork.

PS: Add which merge into the description. It's only the merge with accelerator class branch.
