### ISSUE TITLE
Rename module "twiss_optics" to "optics_analytical" or similar?

### ISSUE THREAD

**Issue by JoschD** [pylhc/Beta-Beat.src#71]
Question stands as title says.
In twiss_optics there is currently the TwissOptics class, which should replace functionality of metaclass and TwissResponse - which generates response matrices.
The two have in common, that they both calculate their results with the help of Franchi's analytical functions.

**Comment by jaimecp89** [comment]
Maybe we want to put a "TwissResponseMadx" (response_pandas.py) in the same place? Then we have all the fullresponse generation together and the "twiss_optics" name still makes sense.

**Comment by JoschD** [comment]
Solved by #104 (similar to @jaimecp89 suggestion)
