### ISSUE TITLE
NaN and 0 in harpy output

### ISSUE THREAD

**Issue by elenafol** [pylhc/Beta-Beat.src#72]
**Problem:** Harpy running without clean option provides output with 0 and NaN,  producing following error in the GUI log:
HoleInOne STDOUT: DataFrame contains non-physical values at Index: [0,..299]
HoleInOne STDOUT: DataFrame contains non-physical values at Index: ['BPMYB.5L2.B1',...]

**sdds file:** /afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-12/LHCB1/Measurements/Beam1@Turn@2017_12_01@14_58_34_838/Beam1@Turn@2017_12_01@14_58_34_838.sdds
**Command:** /afs/cern.ch/work/o/omc/anaconda/bin/python /afs/cern.ch/work/e/efol/public/josch_branch/Beta-Beat.src/hole_in_one/hole_in_one.py --file=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-12/LHCB1/Measurements/Beam1@Turn@2017_12_01@14_58_34_838/Beam1@Turn@2017_12_01@14_58_34_838.sdds --model=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-12/models/LHCB1/flatOpticsTest/twiss.dat --outputdir=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-12/LHCB1/Measurements/Beam1@Turn@2017_12_01@14_58_34_838 harpy --harpy_mode=bpm --tunex=0.27 --tuney=0.322 --nattunex=0.280 --nattuney=0.310 --tunez=0.0 --tolerance=0.01 --tune_clean_limit=1e-5

**Comment by JoschD** [comment]
I was told, that would be corrected with the updates from @awegsche ?

**Comment by awegsche** [comment]
this looks like a problem in an SDDS file. my update will only remove 
NaNs from getbetax/y.out
