### ISSUE TITLE
GetLLM not producing beta from amplitude files

### ISSUE THREAD

**Issue by jaimecp89** [pylhc/Beta-Beat.src#84]
This is what I found in the output log that seem related to beta from amplitude (@anagtv  also reported the same problem):

17:21:45 - GetLlm STDOUT:    INFO |       Calculating beta from amplitude | GetLLM.algorithms.beta
17:21:46 - GetLlm STDERR: /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/model/accelerators/lhc.py:620: FutureWarning: In future versions of pandas, match will change to always return a bool indexer.
17:21:46 - GetLlm STDERR:   return common_bpms.loc[common_bpms.index.str.match("BPM[_,A-Z]*\\.([0-9]+)[R,L].*")]

and then the typical "Abort writing file. Cannot write file until column names and types are set. | utils.tfs_file_writer" in all beta from amplitude files.

**Comment by jaimecp89** [comment]
Is this related to #76 ? @awegsche

**Comment by jaimecp89** [comment]
@lmalina This is fixed right?

**Comment by lmalina** [comment]
Yes, that is fixed. Beta from amplitude was crashing at some point, therefore not producing the output. @anagtv has seen it fixed as well.
