### ISSUE TITLE
Cannot run getLLM for single file

### ISSUE THREAD

**Issue by anagtv** [pylhc/Beta-Beat.src#88]
Running this command 
/afs/cern.ch/work/o/omc/anaconda/bin/python /afs/cern.ch/user/l/lmalina/public/forAna/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB1 --model=/afs/cern.ch/user/g/garciata/work/public/2018-02-20/models/LHCB1/ballistic_model_from_multiturn3/twiss.dat --files=/afs/cern.ch/user/g/garciata/work/public/2018-02-20/LHCB1/Measurements/Beam1@Turn@2017_05_04@03_33_01_981/Beam1@Turn@2017_05_04@03_33_01_981.sdds --output=/afs/cern.ch/user/g/garciata/work/public/2018-02-20/LHCB1/Results/one_file_ballistic --tbtana=SUSSIX --bpmu=mm --lhcphase=1 --errordefs=/afs/cern.ch/user/g/garciata/work/public/2018-02-20/models/LHCB1/ballistic_model_from_multiturn3/error_deff.txt
I got errors for all the BPMs like
 ERROR | >>>ValueError at BPM.30R6.B1 | GetLLM.algorithms.beta

**Comment by awegsche** [comment]
Interesting. This is new, I also saw it since yesterday. Apparently it doesn't assign the errors.

**Comment by jaimecp89** [comment]
Was this finally fixed? Can we close this issue? @awegsche

**Comment by awegsche** [comment]
Well, the original error seemed to come from an invalid errordefs file.
So a crash was somehow to be expected. What should we do?

- let it crash to tell the user that something was wrong (then we can close)
- test if the errordefs file is valid and throw a more precise error message (then we can maybe open a new issue as improvement or TODO?)

**Comment by jaimecp89** [comment]
This is fixed in the new GetLLM and the old one is in the master branch.
