### ISSUE TITLE
broken subprocess call in some files

### ISSUE THREAD

**Issue by awegsche** [pylhc/Beta-Beat.src#99]
In some of the files (e.g. madx/madxrunner.py) you can find a call like:
  ```
    process = subprocess.Popen(madxPath, shell=False, stdin=subprocess.PIPE, stdout=stdout, stderr=stderr)
    process.communicate(stringInput)
```
This does not work. ```process.communicate``` takes an array of bytes (pythons's "bytes-like" object). But ```stringInput``` is, as the name correctly states, a string.

**Comment by jaimecp89** [comment]
The documentation actually states:
Popen.communicate(input=None)
Interact with process: Send data to stdin. Read data from stdout and stderr, until end-of-file is reached. Wait for process to terminate. **The optional input argument should be a string** to be sent to the child process, or None, if no data should be sent to the child.
So the problem has to be somewhere else... can you provide the example file?

**Comment by awegsche** [comment]
The command I am running is:
```
    p = Popen([pythonpath, os.path.join(GetLLMPATH, "madx", "madx_wrapper.py"),
              "--file", "simulate.madx"],cwd=modelfolder)
```
pythonpath = <path to omcpython>
and GetLLMPATH points to a NewGetLLMmaster repository.

**Comment by jaimecp89** [comment]
But I don't understand then... where is the troubling p.communicate()?

**Comment by awegsche** [comment]
in madxrunner, which is called from madx_wrapper I guess

**Comment by awegsche** [comment]
I just realised something: it's calling python 3, why?

Traceback (most recent call last):
  File "/media/awegsche/HDD/CernBox/MyBeta-Beat.src/Beta-Beat.src/madx/madx_wrapper.py", line 149, in <module>
    resolve_and_run_file(_file_to_load, _output_file, _log_file, _madx_path)
  File "/media/awegsche/HDD/CernBox/MyBeta-Beat.src/Beta-Beat.src/madx/madx_wrapper.py", line 53, in resolve_and_run_file
    return run(full_madx_script, log_file, madx_path)
  File "/media/awegsche/HDD/CernBox/MyBeta-Beat.src/Beta-Beat.src/madx/madx_wrapper.py", line 91, in run
    madxPath=madx_path)
  File "/media/awegsche/HDD/CernBox/MyBeta-Beat.src/Beta-Beat.src/madx/madxrunner.py", line 69, in runForInputString
    process.communicate(stringInput)
  File "/home/awegsche/anaconda3/lib/**python3.5**/subprocess.py", line 788, in communicate
    self._stdin_write(input)
  File "/home/awegsche/anaconda3/lib/**python3.5**/subprocess.py", line 741, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'

**Comment by jaimecp89** [comment]
/home/awegsche/anaconda3/lib/*python3.5*  looks like your local
installation of python.
Are you sure that pythonpath is anaconda in OMC? The wrapper doesnt call
python, just madx.

**Comment by awegsche** [comment]
Ah, I found it. At one point, pythonpath was reset to "python".
